version: "{build}"
branches:
  only:
    - main
    - /v\d+\..+/
    - /release.*/
    - appveyor
    - hunter
clone_depth: 100
os: Visual Studio 2019
environment:
  matrix:
    - CUDA_VER: "9.0"
      XHASH_CUDA_ARCHS: "52;60;61;70"
    - CUDA_VER: "11.8"
      XHASH_CUDA_ARCHS: "70;75;80;86;89"
    - CUDA_VER: "13.0"
      XHASH_CUDA_ARCHS: "80;86;89;90"
  HUNTER_CACHE_TOKEN:
    secure: VnpF1MH5MEFvUI5MiMMMFlmbDdst+bfom5ZFVgalYPp/SYDhbejjXJm9Dla/IgpC

cache:
  - C:\CUDA\v9.0 -> appveyor.yml
  - C:\CUDA\v11.8.0 -> appveyor.yml
  - C:\CUDA\v13.0.2 -> appveyor.yml

install: |
  git submodule update --init --recursive
  if "%CUDA_VER%"=="" set CUDA_VER=13.0.2

  if "%CUDA_VER%" == "9.0" set CUDA_ARCHIVE=cuda_9.0.176_win10-exe
  if "%CUDA_VER%" == "11.8.0" set CUDA_ARCHIVE=cuda_11.8.0_522.06_windows.exe
  if "%CUDA_VER%" == "13.0.2" set CUDA_ARCHIVE=cuda_13.0.2_windows.exe

  if NOT EXIST C:\CUDA\v%CUDA_VER% (if "%CUDA_VER%" NEQ "9.0" curl -L https://developer.nvidia.com/compute/cuda/%CUDA_VER%/local_installers/%CUDA_ARCHIVE% -o %CUDA_ARCHIVE%.exe)
  if NOT EXIST C:\CUDA\v%CUDA_VER% (if "%CUDA_VER%" == "9.0" curl -L https://developer.nvidia.com/compute/cuda/%CUDA_VER%/Prod/local_installers/%CUDA_ARCHIVE% -o %CUDA_ARCHIVE%.exe)

  if NOT EXIST C:\CUDA mkdir C:\CUDA
  if NOT EXIST C:\CUDA\v%CUDA_VER% 7z x %CUDA_ARCHIVE%.exe -oC:\CUDA nvcc/* nvrtc*/*
  if NOT EXIST C:\CUDA\v%CUDA_VER% rename C:\CUDA\nvcc v%CUDA_VER%

  set PATH=C:\Python39-x64;C:\Python39-x64\Scripts;%PATH%;C:\CUDA\v%CUDA_VER%\bin
  pip install requests gitpython
  nvcc -V

build_script:
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\VsMSBuildCmd.bat"
  - set GEN=Visual Studio 16 2019
  - set CMAKE_ARGS=-G "%GEN%" -H. -Bbuild -DXHASHCUDA=ON -DAPICORE=ON -DHUNTER_JOBS_NUMBER=%NUMBER_OF_PROCESSORS% -DXHASH_CUDA_ARCHS=%XHASH_CUDA_ARCHS%
  - cmake %CMAKE_ARGS%
  - cmake --build build --config Release --target package
  - ps: |
      . build/hashwarp/buildinfo.ps1
      mv build/hashwarp.zip build/$env:project_name-$env:project_version-cuda$env:CUDA_VER-$env:system_name-$env:system_processor.zip

artifacts:
  - path: build/hashwarp-*.zip
    name: hashwarp
