version: "{build}"

# Run on both Windows and Linux
image:
  - Ubuntu2204
  - Visual Studio 2017

branches:
  only:
    - main
    - /v\d+\..+/
    - /release.*/
    - appveyor
    - hunter

clone_depth: 100

environment:
  matrix:
    - CUDA_VER: "12.2.2"
      # Pascal (60,61,62), Volta (70,72), Turing (75), Ampere (80,86,87),
      # Ada (89), Hopper (90) — all supported by CUDA 12.2
      XHASH_CUDA_ARCHS: "60;61;62;70;72;75;80;86;87;89;90"
  HUNTER_CACHE_TOKEN:
    secure: VnpF1MH5MEFvUI5MiMMMFlmbDdst+bfom5ZFVgalYPp/SYDhbejjXJm9Dla/IgpC

# Cache (Windows CUDA installer). Linux job safely ignores this path.
cache:
  - C:\CUDAInstallers\cuda_12.2.2_537.13_windows.exe -> appveyor.yml

# --------- WINDOWS JOB ----------
for:
  # --------- LINUX JOB (Ubuntu 22.04) ----------
  - matrix:
      only:
        - image: Ubuntu2204
    # OpenCL-only build on Linux (no CUDA toolkits or GPUs on CI runners)
    install: |
      set -e
      git submodule update --init --recursive
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        build-essential cmake ninja-build git \
        ocl-icd-opencl-dev opencl-headers clinfo \
        python3 python3-pip

      python3 -m pip install --disable-pip-version-check --user requests gitpython

      echo "OpenCL platforms (sanity check):"
      clinfo | sed -n '1,80p' || true

      CUDA_VER=12.2.2
      CUDA_RUN=cuda_12.2.2_535.104.05_linux.run
      wget https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/${CUDA_RUN}
      sudo sh ${CUDA_RUN} --silent --toolkit
      export PATH=/usr/local/cuda-12.2/bin:$PATH
      export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64:$LD_LIBRARY_PATH

    build_script: |
      set -e
      # Configure
      cmake -S . -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DHUNTER_JOBS_NUMBER=$(nproc) \
        -DXHASH_CUDA_ARCHS=%XHASH_CUDA_ARCHS%

      cmake --build build --target package -j"$(nproc)"

      # Try to rename the package similarly to Windows
      # Prefer cpack artifacts if present; otherwise zip/tar the build dir.
      pkg="$(ls build/hashwarp-*.tar.gz 2>/dev/null || true)"
      if [ -n "$pkg" ]; then
        # If your CMake generates a buildinfo.sh, source it; otherwise, keep default name
        if [ -f build/hashwarp/buildinfo.sh ]; then
          . build/hashwarp/buildinfo.sh
          new="build/${project_name}-${project_version}-linux-$(uname -m).tar.gz"
          mv "$pkg" "$new"
          echo "Renamed package to: $new"
        else
          echo "Package produced: $pkg"
        fi
      else
        echo "No cpack artifact found; creating a fallback tarball."
        tar czf build/hashwarp-linux-$(uname -m).tar.gz -C build hashwarp || true
      fi

  - matrix:
      only:
        - image: Visual Studio 2017
    install: |
      git submodule update --init --recursive

      rem ----- Map CUDA_VER -> installer filename/URL and subpackages -----
      if "%CUDA_VER%"=="12.2.2" set "CUDA_ARCHIVE=cuda_12.2.2_537.13_windows.exe"
      if "%CUDA_VER%"=="12.2.2" set "CUDA_URL=https://developer.download.nvidia.com/compute/cuda/12.2.2/local_installers/%CUDA_ARCHIVE%"
      if "%CUDA_VER%"=="12.2.2" set "CUDA_SUBPKGS=nvcc_12.2 cudart_12.2 nvrtc_12.2 nvrtc_dev_12.2 nsight_vse_12.2 visual_studio_integration_12.2"

      if not exist "C:\CUDAInstallers" mkdir "C:\CUDAInstallers"
      if exist "C:\CUDAInstallers\%CUDA_ARCHIVE%" echo Using cached installer: C:\CUDAInstallers\%CUDA_ARCHIVE%
      if not exist "C:\CUDAInstallers\%CUDA_ARCHIVE%" echo Downloading %CUDA_ARCHIVE% ...
      if not exist "C:\CUDAInstallers\%CUDA_ARCHIVE%" curl -L "%CUDA_URL%" -o "C:\CUDAInstallers\%CUDA_ARCHIVE%"

      rem ----- Silent install (outer EXE): only needed subpackages, no reboot -----
      "C:\CUDAInstallers\%CUDA_ARCHIVE%" -s %CUDA_SUBPKGS% -n

      rem ----- Set CUDA_PATH and PATH -----
      set "CUDA_MAJOR_MINOR=%CUDA_VER:~0,4%"
      set "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v%CUDA_MAJOR_MINOR%"
      set "PATH=%CUDA_PATH%\bin;%PATH%"

      dir "%CUDA_PATH%\*" /s /b | findstr /i CUDAToolkitConfig.cmake

      nvcc -V

      rem Python tools
      set "PATH=C:\Python39-x64;C:\Python39-x64\Scripts;%PATH%"
      pip install --disable-pip-version-check requests gitpython

    build_script:
      - call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\Common7\Tools\VsMSBuildCmd.bat"
      - set CMAKE_ARGS=-G "Visual Studio 15 2017 Win64" -H. -Bbuild -DHUNTER_JOBS_NUMBER=%NUMBER_OF_PROCESSORS% -DXHASH_CUDA_ARCHS=%XHASH_CUDA_ARCHS%
      - cmake %CMAKE_ARGS%
      - cmake --build build --config Release --target package
      - ps: |
          . build/hashwarp/buildinfo.ps1
          mv build/hashwarp.zip build/$env:project_name-$env:project_version-cuda$env:CUDA_VER-$env:system_name-$env:system_processor.zip

artifacts:
  - path: build/hashwarp-*.zip
    name: hashwarp
  - path: build/hashwarp-*.tar.gz
    name: hashwarp
